### ISSUE TITLE
Cannot invoke "java.util.Map.put(Object, Object)" because "map" is null

### ISSUE THREAD

**Issue by samasword** [happysnaker/mirai-plugin-HRobot#14]
涩图命令抛错
意外地失去了与地球上的通信...
错误原因：Cannot invoke "java.util.Map.put(Object, Object)" because "map" is null

日志:
2022-09-20 15:07:34 W/stderr: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "map" is null
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.utils.IOUtil.sendAndGetResponseMap(IOUtil.java:69)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.utils.IOUtil.sendAndGetResponseMap(IOUtil.java:87)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.api.PixivApi.getSeImagePid(PixivApi.java:75)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.handler.impl.ImageShareMessageEventHandler.doParseSeImage(ImageShareMessageEventHandler.java:166)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.handler.impl.ImageShareMessageEventHandler.handleMessageEvent(ImageShareMessageEventHandler.java:76)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.context.Context.execute(Context.java:98)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.proxy.MessageHandlerProxy.handleMessageEvent(MessageHandlerProxy.java:71)
2022-09-20 15:07:34 W/stderr:   at plugin-3.2.1-SNAPSHOT.mirai.jar//com.happysnaker.starter.HRobotStarter.lambda$Start$0(HRobotStarter.java:59)
2022-09-20 15:07:34 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574)
2022-09-20 15:07:34 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
2022-09-20 15:07:34 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-09-20 15:07:34 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Rain-ziyu** [comment]
这个是访问的连接使用的是Https如果想要修复的话需要修改源码中配置的涩图所用的网站地址
修改原有代码如下public static final String pidApi = "https://api.lolicon.app/setu/v2";
![image](https://user-images.githubusercontent.com/70049441/191423445-ccbf8151-5333-4f65-863f-0cbdf1b982ac.png)

**Comment by samasword** [comment]
能帮忙打个jar包吗 没有下载java编译器

**Comment by happysnaker** [comment]
v3.3 fix
