### ISSUE TITLE
保存配置直接乱码

### ISSUE THREAD

**Issue by loolksama** [happysnaker/mirai-plugin-HRobot#6]
通过指令保存配置后 配置乱码 重启mcl之后mcl直接报错关闭

**Comment by happysnaker** [comment]
请问是使用最新版的插件吗？

**Comment by loolksama** [comment]
yes

**Comment by loolksama** [comment]
保存配置重开后就不能打开了 然后希望加个签到的功能qwq 很喜欢这个插件

**Comment by happysnaker** [comment]
你好，我在 Windows 和 Linux 机上都尝试了几次，先设置一些配置，然后调用保存配置，最后在控制台上重启，但奇怪的是在我的机器上运作良好 [挠头]，并没有出现报错关闭这个问题。

你是否在运行前手动修改过配置文件导致格式错误？yaml 对空格很敏感，你可以前往 [yaml 在线验证](https://www.bejson.com/validators/yaml_editor/) 来验证你的格式是否正确，如果格式出错可能是你编辑时出错了，建议先删除空格再添加空格或从模板中重新编辑，如果格式正确但出错，请问是否可以提供相关截图与错误日志。

通常在 Windows 下编辑换行是 CRLF 格式，但 Yaml 需要 LF 格式，你可以检查一下相关格式。

至于配置乱码的问题，如果是顺序乱了或者格式变了（但 yaml 仍然正确），这是正常的，因为运行时保存本身就是不可控的，如果是文字乱码了（例如变成一堆不认识的字符），这是个大问题......

我建议你一旦使用保存配置后，以后尽量都使用命令格式进行配置，毕竟我设置成 **发送消息进行配置，而不是让你守在电脑前对着控制台进行配置** 这个模式本身就是为了方便进行配置，可以随时随地进行配置，命令应该可以满足绝大多数需求。

最后，非常感谢你的支持，签到积分商城系统我也早就有想法要弄了，只是这个月工作太忙了，没时间设计技术方案，等闲下来就会着手设计，如果有具体想法也可以提 ISSUE 呀！

**Comment by loolksama** [comment]
😭😭你真的好好 我明天去再试试 到时候把log发给你😭😭

**Comment by loolksama** [comment]
现在是没用指令保存 用指令保存 打开发现是棱形+问号那种 不知道为啥😂😂

**Comment by loolksama** [comment]
[91m2022-07-13 06:51:32 W/stderr: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:519)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//com.happysnaker.starter.HRobotStarter.initRobotConfig(HRobotStarter.java:103)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//com.happysnaker.starter.HRobotStarter.Start(HRobotStarter.java:42)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//com.happysnaker.Main.onEnable(Main.java:25)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Loader.start(Loader.java:189)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at org.itxtech.mcl.Loader.main(Loader.java:79)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: Caused by: java.nio.charset.MalformedInputException: Input length = 1
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	at plugin-3.1-SNAPSHOT.mirai.jar//org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
[0m[m
[91m2022-07-13 06:51:32 W/stderr: 	... 41 more
[0m[m

**Comment by loolksama** [comment]
就是保存的时候默认不保存为UTF-8  然后用指令保存就成这样了

**Comment by happysnaker** [comment]
![image](https://user-images.githubusercontent.com/73147033/179254423-aa610fbd-3616-4822-aeb3-e556872a9a89.png)
我在构造写入流的时候，没有指定 utf-8，这是我的疏忽，我会在下个版本加上。

**Comment by loolksama** [comment]
我转码后配置还是无法被读 开启mcl仍然被关闭

**Comment by happysnaker** [comment]
> 我转码后配置还是无法被读 开启mcl仍然被关闭

更新到 3.2 试试，3.2 我将输出流设置为了 UTF-8 格式
